#!/bin/bash
# Quick script to help upload metadata.json to IPFS or get a URL

echo "📤 Metadata Hosting Options:"
echo ""
echo "Option 1: GitHub Gist (Quickest)"
echo "  1. Go to https://gist.github.com"
echo "  2. Create a new public gist"
echo "  3. Paste the contents of metadata.json"
echo "  4. Click 'Create public gist'"
echo "  5. Click 'Raw' button to get the URL"
echo "  6. Copy the URL (looks like: https://gist.githubusercontent.com/.../raw/.../metadata.json)"
echo ""
echo "Option 2: IPFS via NFT.Storage (Free & Permanent)"
echo "  1. Go to https://nft.storage"
echo "  2. Sign up/login (free)"
echo "  3. Upload metadata.json file"
echo "  4. Get the IPFS URL (looks like: https://ipfs.io/ipfs/...)"
echo ""
echo "Option 3: Pinata Cloud (Free IPFS)"
echo "  1. Go to https://pinata.cloud"
echo "  2. Sign up/login (free)"
echo "  3. Upload metadata.json"
echo "  4. Get the IPFS URL"
echo ""
echo "Once you have the URL, set QUICK_METADATA_URI, SOLID_METADATA_URI, or SOLOMON_METADATA_URI in .env"
echo ""
echo "Metadata files: $(pwd)/metadata-quick.json, metadata-solid.json, metadata-solomon.json"
echo ""
echo "To test if your URL works, run:"
echo "  curl -s <YOUR_URL> | python3 -m json.tool"

